export default {
    images: [
        'img/banner-tips.png',
        'img/bg-home.png',
        'img/bg-loading.png',
        'img/bg-main.png',
        'img/btn-close.png',
        'img/btn-custom.png',
        'img/btn-left.png',
        'img/btn-right.png',
        'img/frame1.png',
        'img/frame2.png',
        'img/head-home.png',
        'img/head.png',
        'img/icon-24product.png',
        'img/icon-false.png',
        'img/icon-hand.png',
        'img/icon-plus.png',
        'img/icon-true.png',
        'img/loading元素.png',
        'img/logo-24.png',
        'img/tips-good.png',
        'img/tips-up.png',
        'img/qr-柯婷婷.png',
        'img/qr-杨晓东.png',
        'img/qr-易小琳.png',
        'img/words.png',
        'img/cases/qr_淳风派.png',
        'img/cases/qr_广州地铁.png',
        'img/cases/qr_绿瘦换脸.png',
        'img/cases/qr_希尔顿.png',
        'img/cases/qr_壹点壹刻.png',
        'img/cases/艾美特_0.png',
        'img/cases/爱奇艺_0.png',
        'img/cases/淳风派_0.png',
        'img/cases/广汽三菱_0.png',
        'img/cases/广州地铁_0.jpg',
        'img/cases/花生_0.png',
        'img/cases/集卡_0.png',
        'img/cases/龙岗_0.png',
        'img/cases/绿瘦换脸_0.png',
        'img/cases/美宜佳_0.jpg',
        'img/cases/深圳晚报_0.png',
        'img/cases/世界杯竞猜_0.png',
        'img/cases/贪吃蛇_0.png',
        'img/cases/希尔顿_0.jpg',
        'img/cases/携程点灯_0.png',
        'img/cases/壹点壹刻_0.png'

    ],
    mainData: [
        {
            title: '美宜佳',
            hasTag: false,
            posterImg: 'img/cases/美宜佳_0.jpg',
            positiveTips: '流量大<br>四合一游戏<br>细节丰富',
            nagativeTips: '体验差<br>兼容差<br>没想法',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/美宜佳_1.jpg', 'img/cases/美宜佳_2.jpg', 'img/cases/美宜佳_3.jpg'],
            qr: 'img/404.jpg',
        },
        {
            title: '希尔顿滑雪',
            hasTag: false,
            posterImg: 'img/cases/希尔顿_0.jpg',
            positiveTips: 'Phaser<br>横屏适配<br>大量动画',
            nagativeTips: '时间赶<br>防刷奖<br>性能差',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/希尔顿_1.jpg', 'img/cases/希尔顿_2.jpg', 'img/cases/希尔顿_3.jpg'],
            qr: 'img/cases/qr_希尔顿.png',
        },
        {
            title: '壹点壹刻',
            hasTag: false,
            posterImg: 'img/cases/壹点壹刻_0.png',
            positiveTips: '微信录音<br>音乐评分<br>设备兼容',
            nagativeTips: '效果差<br>兼容差<br>不敢创新',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/壹点壹刻_1.png', 'img/cases/壹点壹刻_2.png', 'img/cases/壹点壹刻_3.png', 'img/cases/壹点壹刻_4.png'],
            qr: 'img/cases/qr_壹点壹刻.png',
        },   
        {
            title: '广州地铁',
            hasTag: false,
            posterImg: 'img/cases/广州地铁_0.jpg',
            positiveTips: '信息查询<br>swiper.js<br>app嵌入',
            nagativeTips: '兼容性差<br>动画卡顿<br>无细节',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/广州地铁_1.jpg', 'img/cases/广州地铁_2.jpg', 'img/cases/广州地铁_3.jpg'],
            qr: 'img/cases/qr_广州地铁.png',
        },
        {
            title: '贪吃蛇',
            hasTag: false,
            posterImg: 'img/cases/贪吃蛇_0.png',
            positiveTips: 'Phaser<br>平滑流畅<br>细节丰富',
            nagativeTips: '游戏卡顿<br>兼容差<br>不敢创新',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/贪吃蛇_1.png', 'img/cases/贪吃蛇_2.png', 'img/cases/贪吃蛇_3.png'],
            qr: 'img/404.jpg',
        },
        {
            title: '爱奇艺投票',
            hasTag: false,
            posterImg: 'img/cases/爱奇艺_0.png',
            positiveTips: '视频图片<br>内部活动<br>资源上传',
            nagativeTips: '资源卡顿<br>兼容差<br>数据收集',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/爱奇艺_1.png', 'img/cases/爱奇艺_2.png', 'img/cases/爱奇艺_3.png'],
            qr: 'img/404.jpg',
        },
        {
            title: '花生答题',
            hasTag: false,
            posterImg: 'img/cases/花生_0.png',
            positiveTips: '后端开发<br>Koa<br>大牛审核',
            nagativeTips: '服务崩溃<br>响应慢<br>500',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/花生_1.png', 'img/cases/花生_2.png', 'img/cases/花生_3.png'],
            qr: 'img/404.jpg',
        },
        {
            title: '淳风派',
            hasTag: false,
            posterImg: 'img/cases/淳风派_0.png',
            positiveTips: '大流量<br>丰富动画<br>多游戏',
            nagativeTips: '底层编写<br>性能差<br>不敢尝鲜',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/淳风派_1.png', 'img/cases/淳风派_2.png', 'img/cases/淳风派_3.png', 'img/cases/淳风派_4.png'],
            qr: 'img/cases/qr_淳风派.png',
        },
        {
            title: '龙岗展示',
            hasTag: false,
            posterImg: 'img/cases/龙岗_0.png',
            positiveTips: '视频兼容<br>仿IOS<br>细节丰富',
            nagativeTips: '效果差<br>兼容差<br>结构清晰',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/龙岗_1.png', 'img/cases/龙岗_2.png', 'img/cases/龙岗_3.png'],
            qr: 'img/404.jpg',
        },
        {
            title: '绿瘦换脸',
            hasTag: false,
            posterImg: 'img/cases/绿瘦换脸_0.png',
            positiveTips: '海报合成<br>照片换脸<br>预加载',
            nagativeTips: '改改改<br>二次修改<br>难缠客户',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/绿瘦换脸_1.png', 'img/cases/绿瘦换脸_2.png', 'img/cases/绿瘦换脸_3.png', 'img/cases/绿瘦换脸_4.png'],
            qr: 'img/cases/qr_绿瘦换脸.png',
        },
        {
            title: '携程点灯',
            hasTag: false,
            posterImg: 'img/cases/携程点灯_0.png',
            positiveTips: 'Phaser<br>好友助力<br>架构良好',
            nagativeTips: '效果差<br>兼容差<br>反复修改',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/携程点灯_1.png', 'img/cases/携程点灯_2.png', 'img/cases/携程点灯_3.png'],
            qr: 'img/404.jpg',
        },
        {
            title: '集卡助力',
            hasTag: false,
            posterImg: 'img/cases/集卡_0.png',
            positiveTips: '好友助力<br>翻牌效果<br>自制动画',
            nagativeTips: '逻辑混乱<br>出bug<br>兼容差',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/集卡_1.png', 'img/cases/集卡_2.png', 'img/cases/集卡_3.png'],
            qr: 'img/404.jpg',
        },
        {
            title: '三菱找不同',
            hasTag: false,
            posterImg: 'img/cases/广汽三菱_0.png',
            positiveTips: 'Dom游戏<br>效果流畅<br>首次开发',
            nagativeTips: '数据错乱<br>兼容差<br>效果差',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/广汽三菱_1.png', 'img/cases/广汽三菱_2.png', 'img/cases/广汽三菱_3.png'],
            qr: 'img/404.jpg',
        },
        {
            title: '深圳晚报',
            hasTag: false,
            posterImg: 'img/cases/深圳晚报_0.png',
            positiveTips: 'Phser<br>首次开发<br>动画流畅',
            nagativeTips: '效果差<br>兼容差<br>不敢创新',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/深圳晚报_1.png', 'img/cases/深圳晚报_2.png', 'img/cases/深圳晚报_3.png'],
            qr: 'img/404.jpg',
        },
        {
            title: '世界杯竞猜',
            hasTag: false,
            posterImg: 'img/cases/世界杯竞猜_0.png',
            positiveTips: '蹭热点<br>平台模板<br>投票兑奖',
            nagativeTips: '效果差<br>兼容差<br>不敢创新',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/世界杯竞猜_1.png', 'img/cases/世界杯竞猜_2.png', 'img/cases/世界杯竞猜_3.png'],
            qr: 'img/404.jpg',
        },
        {
            title: '艾美特',
            hasTag: false,
            posterImg: 'img/cases/艾美特_0.png',
            positiveTips: '蹭热点<br>多样性<br>录制视频',
            nagativeTips: '不入戏<br>不敢创新<br>一成不变',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/艾美特_1.png', 'img/cases/艾美特_2.png', 'img/cases/艾美特_3.png'],
            qr: 'img/404.jpg',
        }
    ]
};
