export default {
    images: [
        'img/ad1.png',
        'img/banner-tips.png',
        'img/bg-home.png',
        'img/bg-loading.png',
        'img/bg-main.png',
        'img/btn-close.png',
        'img/btn-custom.png',
        'img/btn-left.png',
        'img/btn-right.png',
        'img/frame1.png',
        'img/frame2.png',
        'img/head-home.png',
        'img/head.png',
        'img/icon-24product.png',
        'img/icon-false.png',
        'img/icon-hand.png',
        'img/icon-plus.png',
        'img/icon-true.png',
        'img/loading元素.png',
        'img/logo-24.png',
        'img/tips-good.png',
        'img/tips-up.png',
        'img/tips-视觉控.png',
        'img/tips-互动交互.png',
        'img/tips-全景合成.png',
        'img/tips-录屏剧情.png',
        'img/tips-恶搞动画.png',
        'img/tips-投票生成.png',
        'img/tips-换脸生成.png',
        'img/tips-真人互动.png',
        'img/tips-视频生成.png',
        'img/tips-长屏滑动.png',
        'img/tips-闯关游戏.png',
        'img/tips-音频录制.png',
        'img/qr-柯婷婷.png',
        'img/qr-杨晓东.png',
        'img/qr-易小琳.png',
        'img/words.png',
    ],
    mainData: [
        {
            hasTag: false,
            posterImg: 'img/cases/全景合成-封面.png',
            typeImg: 'img/tips-全景合成.png',
            positiveTips: '经费充裕<br>场景展示<br>科幻酷炫',
            nagativeTips: '预算低<br>明天就要<br>改改改',
            mainTips: '活动推广<br>趣味游戏',
            swiper: ['img/cases/全景合成-详情1.png', 'img/cases/全景合成-详情2.png', 'img/cases/全景合成-详情3.png', 'img/cases/全景合成-详情4.png'],
            qr: 'img/cases/qr-全景合成.png',
        },
        {
            hasTag: false,
            posterImg: 'img/cases/真人互动-封面.png',
            typeImg: 'img/tips-真人互动.png',
            positiveTips: '明星视频<br>火爆预热<br>视频互动',
            nagativeTips: '改改改<br>渣画质<br>强插硬广',
            mainTips: '产品介绍<br>真人视频',
            swiper: ['img/cases/真人互动-详情1.png', 'img/cases/真人互动-详情2.png', 'img/cases/真人互动-详情3.png', 'img/cases/真人互动-详情4.png'],
            qr: 'img/cases/qr-真人互动.png',
        },
        {
            hasTag: false,
            posterImg: 'img/cases/视频生成-封面.png',
            typeImg: 'img/tips-视频生成.png',
            positiveTips: '脑洞大开<br>场景展示<br>活动预热',
            nagativeTips: '改改改<br>强插硬广<br>严肃呆板',
            mainTips: '活动推广<br>视频素材',
            swiper: ['img/cases/视频生成-详情1.png', 'img/cases/视频生成-详情2.png', 'img/cases/视频生成-详情3.png', 'img/cases/视频生成-详情4.png'],
            qr: 'img/cases/qr-视频生成.png',
        },
        {
            hasTag: false,
            posterImg: 'img/cases/互动交互-封面.png',
            typeImg: 'img/tips-互动交互.png',
            positiveTips: '新品上线<br>火爆预热<br>有自信',
            nagativeTips: '没自信<br>强插硬广<br>单纯炫技',
            mainTips: '品牌推广<br>新品介绍',
            swiper: ['img/cases/互动交互-详情1.png', 'img/cases/互动交互-详情2.png', 'img/cases/互动交互-详情3.png', 'img/cases/互动交互-详情4.png'],
            qr: 'img/cases/qr-互动交互.png',
        },
        {
            hasTag: false,
            posterImg: 'img/cases/恶搞动画-封面.png',
            typeImg: 'img/tips-恶搞动画.png',
            positiveTips: '扎心共鸣<br>幽默搞笑<br>手绘画风',
            nagativeTips: '改改改<br>强插硬广<br>呆板无趣',
            mainTips: '品牌推广<br>提高销量',
            swiper: ['img/cases/恶搞动画-详情1.png', 'img/cases/恶搞动画-详情2.png', 'img/cases/恶搞动画-详情3.png', 'img/cases/恶搞动画-详情4.png'],
            qr: 'img/cases/qr-恶搞动画.png',
        },
        {
            hasTag: false,
            posterImg: 'img/cases/3D视觉控-封面.png',
            typeImg: 'img/tips-视觉控.png',
            positiveTips: '预算高<br>外貌协会<br>有耐心',
            nagativeTips: '改改改<br>每天要<br>预算低',
            mainTips: '品牌推广<br>产品推广',
            swiper: ['img/cases/3D视觉控-详情1.png', 'img/cases/3D视觉控-详情2.png', 'img/cases/3D视觉控-详情3.png', 'img/cases/3D视觉控-详情4.png'],
            qr: 'img/cases/qr-3D视觉控.png',
        },
        {
            hasTag: true,
            posterImg: 'img/cases/长屏滑动-封面.png',
            typeImg: 'img/tips-长屏滑动.png',
            positiveTips: '展示品牌<br>外貌协会<br>多个品牌',
            nagativeTips: '改改改<br>场景生硬<br>呆板无趣',
            mainTips: '多品牌推广<br>周年活动',
            swiper: ['img/cases/长屏滑动-详情1.png', 'img/cases/长屏滑动-详情2.png', 'img/cases/长屏滑动-详情3.png', 'img/cases/长屏滑动-详情4.png'],
            qr: 'img/cases/qr-长屏滑动.png',
        },
        {
            hasTag: true,
            posterImg: 'img/cases/音频录制-封面.png',
            typeImg: 'img/tips-音频录制.png',
            positiveTips: '听觉互动<br>新颖交互<br>预算充裕',
            nagativeTips: '明天就要<br>强插硬广<br>预算低',
            mainTips: '品牌推广<br>助力优惠',
            swiper: ['img/cases/音频录制-详情1.png', 'img/cases/音频录制-详情2.png', 'img/cases/音频录制-详情3.png', 'img/cases/音频录制-详情4.png'],
            qr: 'img/cases/qr-音频录制.png',
        },
        {
            hasTag: false,
            posterImg: 'img/cases/闯关游戏-封面.png',
            typeImg: 'img/tips-闯关游戏.png',
            positiveTips: '脑洞大开<br>趣味生动<br>奖品丰厚',
            nagativeTips: '明天就要<br>犹豫不定<br>无聊呆板',
            mainTips: '抽奖发奖<br>福利推广',
            swiper: ['img/cases/闯关游戏-详情1.png', 'img/cases/闯关游戏-详情2.png', 'img/cases/闯关游戏-详情3.png', 'img/cases/闯关游戏-详情4.png'],
            qr: 'img/cases/qr-闯关游戏.png',
        },
        {
            hasTag: true,
            posterImg: 'img/cases/投票生成-封面.png',
            typeImg: 'img/tips-投票生成.png',
            positiveTips: '新品推广<br>蹭热点<br>多人参与',
            nagativeTips: '不看颜值<br>廉价奖品<br>强插硬广',
            mainTips: '品牌推广<br>投票领奖',
            swiper: ['img/cases/投票生成-详情1.png', 'img/cases/投票生成-详情2.png', 'img/cases/投票生成-详情3.png', 'img/cases/投票生成-详情4.png'],
            qr: 'img/cases/qr-投票生成.png',
        },
        {
            hasTag: true,
            posterImg: 'img/cases/换脸生成-封面.png',
            typeImg: 'img/tips-换脸生成.png',
            positiveTips: '预算高<br>蹭热点<br>品牌推广',
            nagativeTips: '改改改<br>明天就要<br>预算低',
            mainTips: '品牌推广<br>事件营销',
            swiper: ['img/cases/换脸生成-详情1.png', 'img/cases/换脸生成-详情2.png', 'img/cases/换脸生成-详情3.png', 'img/cases/换脸生成-详情4.png'],
            qr: 'img/cases/qr-换脸生成.png',
        },
        {
            hasTag: true,
            posterImg: 'img/cases/录屏剧情-封面.png',
            typeImg: 'img/tips-录屏剧情.png',
            positiveTips: '预算高<br>蹭热点<br>品牌推广',
            nagativeTips: '改改改<br>放不开<br>脑洞小',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/录屏剧情-详情1.png', 'img/cases/录屏剧情-详情2.png', 'img/cases/录屏剧情-详情3.png', 'img/cases/录屏剧情-详情4.png'],
            qr: 'img/cases/qr-录屏剧情.png',
        }
    ]
};
