export default {
    images: [
        'img/ad1.png',
        'img/banner-tips.png',
        'img/bg-home.png',
        'img/bg-loading.png',
        'img/bg-main.png',
        'img/btn-close.png',
        'img/btn-custom.png',
        'img/btn-left.png',
        'img/btn-right.png',
        'img/frame1.png',
        'img/frame2.png',
        'img/head-home.png',
        'img/head.png',
        'img/icon-24product.png',
        'img/icon-false.png',
        'img/icon-hand.png',
        'img/icon-plus.png',
        'img/icon-true.png',
        'img/loading元素.png',
        'img/logo-24.png',
        'img/tips-good.png',
        'img/tips-up.png',
        'img/qr-柯婷婷.png',
        'img/qr-杨晓东.png',
        'img/qr-易小琳.png',
        'img/words.png',
    ],
    mainData: [
        {
            hasTag: false,
            posterImg: 'img/cases/广州地铁_0.jpg',
            typeImg: 'img/tips-录屏剧情.png',
            positiveTips: '预算高<br>蹭热点<br>品牌推广',
            nagativeTips: '改改改<br>放不开<br>脑洞小',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/广州地铁_1.jpg', 'img/cases/广州地铁_2.jpg', 'img/cases/广州地铁_3.jpg', 'img/cases/广州地铁_4.jpg'],
            qr: 'img/cases/qr_广州地铁.png',
        },
        {
            hasTag: false,
            posterImg: 'img/cases/绿瘦换脸_0.png',
            typeImg: 'img/tips-录屏剧情.png',
            positiveTips: '预算高<br>蹭热点<br>品牌推广',
            nagativeTips: '改改改<br>放不开<br>脑洞小',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/绿瘦换脸_1.png', 'img/cases/绿瘦换脸_2.png', 'img/cases/绿瘦换脸_3.png', 'img/cases/绿瘦换脸_4.png'],
            qr: 'img/cases/qr_绿瘦换脸.png',
        },
        {
            hasTag: false,
            posterImg: 'img/cases/美宜佳_0.png',
            typeImg: 'img/tips-录屏剧情.png',
            positiveTips: '预算高<br>蹭热点<br>品牌推广',
            nagativeTips: '改改改<br>放不开<br>脑洞小',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/美宜佳_1.png', 'img/cases/美宜佳_2.png', 'img/cases/美宜佳_3.png', 'img/cases/美宜佳_4.png'],
            qr: 'img/cases/qr_美宜佳.png',
        },
        {
            hasTag: false,
            posterImg: 'img/cases/希尔顿_0.jpg',
            typeImg: 'img/tips-录屏剧情.png',
            positiveTips: '预算高<br>蹭热点<br>品牌推广',
            nagativeTips: '改改改<br>放不开<br>脑洞小',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/希尔顿_1.jpg', 'img/cases/希尔顿_2.jpg', 'img/cases/希尔顿_3.jpg', 'img/cases/希尔顿_4.jpg'],
            qr: 'img/cases/qr_希尔顿.jpg',
        },
        {
            hasTag: false,
            posterImg: 'img/cases/壹点壹刻_0.png',
            typeImg: 'img/tips-录屏剧情.png',
            positiveTips: '预算高<br>蹭热点<br>品牌推广',
            nagativeTips: '改改改<br>放不开<br>脑洞小',
            mainTips: '产品推广<br>事件营销',
            swiper: ['img/cases/壹点壹刻_1.png', 'img/cases/壹点壹刻_2.png', 'img/cases/壹点壹刻_3.png', 'img/cases/壹点壹刻_4.png'],
            qr: 'img/cases/qr_壹点壹刻.png',
        }
    ]
};
